Multithreaded file uploader
Tricky-Compression/Frontend pull request #1
Opened 2022-05-28 23:42 UTC by APozdniakov

2022-05-29 00:35 UTC, j-zo requested changes

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/entity/ChunkData.java
> +    private long chunkNumber;
Почему long, инта не хватит?

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/entity/ChunkData.java
> +    public ByteBuffer getData() {
dat'у могут модифицировать снаружи. для соблюдения принципов инкапсуляции лучше не открывать доступ к буферу извне

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/Compressor.java
>      private static final int LEVEL = Zstd.maxCompressionLevel();
(опционально) можно было бы передавать этот параметр в конструктор компрессора, при инициализации

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/Compressor.java
>          return output;
зачем надо было делать эти методы статичными?

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +    private static final long CHUNK_SIZE = 4096;
почему 4096 и почему long?

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +            failure.set(true);
тут нужно использовать compareAndSet
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicBoolean.html

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +                failure.set(true);
same as above

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +                failure.set(true);
same as above

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        FileChannel channel = FileChannel.open(Paths.get(filename), StandardOpenOption.READ).position(0);
все открытые каналы/ресурсы нужно закрывать
т.е. try(FileChannel channel = FileChannel.open(...)) {
}

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        int numberOfTasks = (int) ((fileSize + CHUNK_SIZE - 1) / CHUNK_SIZE);
разве не надо просто размер файла разделить на chunk_size?

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        FileChannel channel = FileChannel.open(Paths.get(filename), StandardOpenOption.READ).position(0);
Безопаснее будет в каждой UploadChunkTask создавать новый FileChannel
см. абзац про конкуретность 
https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +                        Model.post(url, chunkData, callback);
Все еще отправка по сети происходит в одном потоке, что на корню убивает изначальную идею о конкурентной отправке.
post тоже нужно подвинуть в UploadChunkTask и ожидать в этом потоке результаты постов

2022-05-29 00:35 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        new Thread(() -> {
Зачем здесь было создавать отдельный поток?

2022-05-29 11:32 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +    private static final long CHUNK_SIZE = 4096;
Пока просто константа пальцем в небо, потом будем подбирать с помощью таймстемпов
Лонг заменю на инт

2022-05-29 11:34 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/entity/ChunkData.java
> +    private long chunkNumber;
Согласен, поменял

2022-05-29 11:41 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        int numberOfTasks = (int) ((fileSize + CHUNK_SIZE - 1) / CHUNK_SIZE);
Это деление с округлением вверх. Так, например, файл размера 4097 нужно отправить двумя запросами по 4096  и 1 байт

2022-05-29 11:43 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        new Thread(() -> {
Потому что в противном случае `latch.await()` будет усыплять основной поток

2022-05-29 11:47 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +                        Model.post(url, chunkData, callback);
В этой библиотеке, насколько я понял, в методе .enqueue(callback) (который вызывается в Model.post) внутри создается свой поток, который ожидает ответа и затем вызывает callback. Но все-таки согласен, post стоит переместить

2022-05-29 12:20 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/Compressor.java
>          return output;
Ну если можно, то почему бы и нет)

2022-05-29 12:22 UTC, APozdniakov commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        new Thread(() -> {
Убрал защелку совсем, потому что если в где-то в таске произойдет что-то плохое, то защелка не опустится и `latch.await()` навсегда заблокируется. Но тем не менее `future.get()` блокирует поток, до тех пор пока задание не выполнится

2022-05-31 12:42 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/Compressor.java
>          return output;
При юнит-тестировании для статичных методов сложнее делать заглушки.

2022-05-31 14:51 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        new Thread(() -> {
Да, сейчас в принципе похоже на правду. Теперь можно тестить

2022-05-31 14:52 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        new Thread(() -> {
Мерджить лучше после успешного тестирования

2022-06-01 15:03 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +            } catch (InterruptedException ignored) {
Здесь лучше писать в логи не только успешный сценарий, но и ошибку, если что-то не отправилось

2022-06-22 16:05 UTC, j-zo commented on app/src/main/java/ru/tricky_compression/model/FileUploader.java
> +        public Long call() {
Если что, здесь можно возвращать не только статус, но и целый объект или хотя бы enum)

2022-06-23 17:43 UTC, closed without merging